server:
  port: 32300

mybatis-plus:
  mapper-locations: classpath:/mapper/server/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.33.1:8848
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.33.3:3306/idas_server1?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
